### ISSUE TITLE
Remote is always assumed to be named "origin"

### ISSUE THREAD

**Issue by theAkito** [ThisIsManta/vscode-git-grace#3]
```
git --no-pager fetch --prune origin
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Getting this error on most of the repositories I develop on, as soon as I open them in the IDE, since the default remote is usually not named "origin".
Apparently, there is a prune going on there, therefore a name has to be supplied.

It would be nice to make this behaviour adjustable to the user's need by providing an entry in the Settings, so the user can, for example, turn off the pruning.

**Comment by ThisIsManta** [comment]
Hi @theAkito, would you send me a sample of your `.git/config` file? You might want to remove the `url =`, of course.

![image](https://user-images.githubusercontent.com/5592654/126753849-ccb8f9c6-7354-432b-840e-cd7ef10250d9.png)

**Comment by ThisIsManta** [comment]
Also the output of `git remote -v`, please. Here is my sample.

![image](https://user-images.githubusercontent.com/5592654/126754137-3120eea5-4727-4bd7-8501-8f4255468bf8.png)

**Comment by ThisIsManta** [comment]
Closed due to inactivity.
